### ISSUE TITLE
Update with new Characters?

### ISSUE THREAD

**Issue by smearedyam** [infomofo/mpq-party-planner#11]
I love this page, and would love to have all the updated characters.

**Comment by infomofo** [comment]
Ugh sorry, I stopped playing the game almost a year ago! If it hasn't changed too much I'll try and take a look this weekend to see if I can update the tool.

**Comment by DeputyLunchbox** [comment]
I agree 100%.  Your list is by far the best and easiest to use.  The community would love an update!

**Comment by DeputyLunchbox** [comment]
I would easily pay for an app of your list as well.

**Comment by smearedyam** [comment]
@infomofo if I update that characters.json file, would you update it on your page?  

(I've tried cloning and forking your repo, but I don't know what I'm doing yet with Angular.. plus I don't know if any of this will work on GitHub pages as I don't know what server they use and it looks like you were using Apache/Grunt/Other stuff I don't know about.. any help to get me going on this I'd appreciate.. I'm in school for Computer Science, but am still getting familiar with some of these tools.. but I'd love to get this going and offer and support this for the MPQ community)

**Comment by infomofo** [comment]
Send me a pull request for the updated JSON file and I'll take a look

**Comment by infomofo** [comment]
This was addressed by @wrefflefloyfjor in #12
