### ISSUE TITLE
Updated Characters?

### ISSUE THREAD

**Issue by wrefflefloyfjor** [infomofo/mpq-party-planner#12]
Hello, Friend!

First off, I used to love your page, it was exactly what I wanted in a supplementary guidebook.

I've created a file (in the style of your original characters sheet) containing all of the characters they added since you stopped updating. 

I was wondering: if I shipped the updated list to you, would you be able to add it to the existing characters?

I'm beginning to work on a personal project that will replicate some of the things your site did, but one that I could continuously update with the same facemelting pace D3 releases new characters. But, since I'm only familiar with Python and some JavaScript, it may take learning a new language to code it. I figured this might make some people (like me) happy until then.

Cheers,
Wrefflefloyfjor.

**Comment by infomofo** [comment]
Sure if you want you can open a PR with the new json file or link me a gist with the new json file. Thanks!

**Comment by wrefflefloyfjor** [comment]
https://gist.github.com/wrefflefloyfjor/e8ba832149db53164c77696c6c429b0b

This only contains the characters you didn't already have, so you'll want to add it to the others. I've checked it over and didn't notice any errors, but it was just me and there might be a few.

Thanks for helping the community ;-)

-Wreffle

**Comment by infomofo** [comment]
Thanks @wrefflefloyfjor I was able to add the characters easily to my json file and redeploy! Happy MPQing!

**Comment by wrefflefloyfjor** [comment]
That is awesome!
You've made me so happy.
Seeing it deployed is rewarding for the time I put into it, it feels great.

I see a few typos I made: i used find/replace when I noticed your colors were lowercase and that caused some errors I didn't think of (green Goblin, red Hulk, black Widow, etc...) I'll fix those in my file just in case.

Also, I notice some of the pics links are broke, but I don't really notice a problem with them.. do you have a suggestion of how I could fix that on my end?

Even if you don't respond: Thank you so much for adding these!

**Comment by infomofo** [comment]
Absolutely, I'm glad you were able to make the changes! I don't play anymore so I'm not up to speed with the newer characters in the game, but I'm glad that people still find the tool useful!

So if you would like to make any updates you should be able to suggest edits directly on this file while you're logged into github via a pull request:

https://github.com/infomofo/mpq-party-planner/blob/master/app/data/characters.json

You can learn more about how to use the github interface to make pull requests here: https://help.github.com/articles/creating-a-pull-request/
